version: "3.8"

services:

  start-dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rabbitmq_service
    command: rabbitmq_service:5672

  rabbitmq_service:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql_db_service:
    container_name: mysql_db
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d

  mongo_db_service:
    container_name: mongo_db
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"

  azurite_service:
    container_name: azurite
    image: "mcr.microsoft.com/azure-storage/azurite"
    hostname: azurite
    restart: always
    volumes:
      - azurite:/data
    expose:
      - "10000"
      - "10001"
    ports:
      - "10000:10000"
      - "10001:10001"

  user_service:
    container_name: user
    build:
      context: ../src/Services
      dockerfile: Instagram.Services.User/Dockerfile
    restart: always
    environment:
      JWT__SECRETKEY: "${JWT_SECRET_KEY}"

      # Database
      DB_PASSWORD: "${DB_PASSWORD}"
      ConnectionStrings__DefaultConnection: "Server=mysql_db_service;Database=InstagramServicesUser;Uid=root;Password=${DB_PASSWORD};"

      # RabbitMQ
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
      rabbitmq__Password: "${RABBITMQ_PASSWORD}"

    expose:
      - "9000"

    depends_on:
      - mysql_db_service
      - rabbitmq_service

  post_service:
    container_name: post
    build:
      context: ../src/Services
      dockerfile: Instagram.Services.Post/Dockerfile
    restart: always
    environment:
      JWT__SECRETKEY: "${JWT_SECRET_KEY}"

      # Database
      DB_PASSWORD: "${DB_PASSWORD}"
      ConnectionStrings__DefaultConnection: "Server=mysql_db_service;Database=InstagramServicesPost;Uid=root;Password=${DB_PASSWORD};"

      # RabbitMQ
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
      rabbitmq__Password: "${RABBITMQ_PASSWORD}"

      # Azurite
      AZURITE_ACCOUNT_KEY: "${AZURITE_ACCOUNT_KEY}"

    expose:
      - "9001"

    volumes:
      - pictures:/home/mranonymous/Pictures

    depends_on:
      - mysql_db_service
      - user_service
      - azurite_service
      - rabbitmq_service

  newsfeed_service:
    container_name: newsfeed
    build:
      context: ../src/Services
      dockerfile: Instagram.Services.Newsfeed/Dockerfile
    restart: always
    environment:
      JWT__SECRETKEY: "${JWT_SECRET_KEY}"

      # RabbitMQ
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
      rabbitmq__Password: "${RABBITMQ_PASSWORD}"

    expose:
      - "9002"

    depends_on:
      - mongo_db_service
      - user_service
      - post_service
      - rabbitmq_service

  nginx_service:
    container_name: nginx_gateway
    build:
      context: ../src/ApiGateway
    restart: always

    depends_on:
      - user_service
      - post_service
      - newsfeed_service

    volumes:
      - ../src/ApiGateway/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "8080:80"
      - "4430:443"

  web_service:
    container_name: web
    build:
      context: ../src/Web
    restart: always

    volumes:
      - ../src/Web:/app
      - web_node_modules:/app/node_modules

    expose:
      - "3000"

    environment:
      # DONT USE IN PRODUCTION:
      # Required because of Invalid Host Header during local development
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"

    stdin_open: true

networks:
  default:
    driver: bridge

volumes:
  mysql:
  mongo:
  azurite:
  pictures:
  web_node_modules: